CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS app;
CREATE SCHEMA IF NOT EXISTS audit;
CREATE SCHEMA IF NOT EXISTS simulation;
CREATE SCHEMA IF NOT EXISTS infra;

DO $$
BEGIN
  CREATE TYPE app.contact_status AS ENUM ('INVITED', 'PENDING_KEYING', 'ACTIVE', 'REMOVED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$
BEGIN
  CREATE TYPE app.package_status AS ENUM ('UPLOADING', 'VALIDATING', 'READY', 'ACTIVE', 'SUPERSEDED', 'DELETE_PENDING', 'DELETED', 'FAILED', 'ABORTED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$
BEGIN
  CREATE TYPE app.workflow_kind AS ENUM ('DEATH_CONFIRMATION', 'PASSWORD_RECOVERY');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$
BEGIN
  CREATE TYPE app.workflow_state AS ENUM ('AWAITING_CONFIRMATIONS', 'GRACE_PERIOD', 'AWAITING_APPROVALS', 'REWRAP_PENDING', 'DEATH_CONFIRMING', 'RELEASE_PENDING', 'PASSWORD_RECOVERY', 'COMPLETED', 'CANCELLED', 'EXPIRED', 'RELEASED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$
BEGIN
  CREATE TYPE app.workflow_decision AS ENUM ('DEATH_LIKELY', 'ALIVE', 'RECOVERY_APPROVE');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$
BEGIN
  CREATE TYPE app.notification_status AS ENUM ('QUEUED', 'SENDING', 'RETRY_WAIT', 'SENT', 'FAILED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$
BEGIN
  CREATE TYPE app.token_purpose AS ENUM ('CONTACT_INVITE', 'CONTACT_PASSWORD_CHANGE', 'ADMIN_RECOVERY_START', 'ADMIN_PASSWORD_RESET', 'ADMIN_PASSWORD_RESET_CODE', 'EMAIL_ACTION_ENTRY');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
