DROP TRIGGER IF EXISTS public_events_immutable ON audit.public_events;
DROP TRIGGER IF EXISTS private_events_immutable ON audit.private_events;
DROP TRIGGER IF EXISTS publications_immutable ON app.publications;
DROP FUNCTION IF EXISTS app.reject_immutable_mutation();
ALTER TABLE app.email_verification_codes DROP CONSTRAINT IF EXISTS email_verification_notification_fk;
ALTER TABLE app.contact_invitations DROP CONSTRAINT IF EXISTS contact_invitations_notification_fk;
DROP INDEX IF EXISTS audit.idx_public_audit_publication;
DROP INDEX IF EXISTS audit.idx_private_audit_occurred;
DROP INDEX IF EXISTS app.idx_sessions_actor;
DROP INDEX IF EXISTS app.idx_outbox_delivery;
DROP INDEX IF EXISTS app.idx_notifications_delivery;
DROP INDEX IF EXISTS app.idx_workflow_actions_workflow_decision;
DROP INDEX IF EXISTS app.idx_workflow_contacts_workflow;
DROP INDEX IF EXISTS app.idx_workflows_kind_started;
DROP INDEX IF EXISTS app.idx_workflows_state_release;
DROP INDEX IF EXISTS app.idx_packages_status_version;
DROP INDEX IF EXISTS app.idx_generations_vault_status;
DROP INDEX IF EXISTS app.idx_invitations_contact_expiry;
DROP INDEX IF EXISTS app.idx_contacts_status;
DROP INDEX IF EXISTS app.idx_schedules_deadline;
DROP INDEX IF EXISTS app.idx_check_ins_checked_at;
DROP INDEX IF EXISTS app.uq_one_formal_workflow;
DROP INDEX IF EXISTS app.uq_one_active_checkin_schedule;
DROP INDEX IF EXISTS app.uq_one_active_package;
DROP INDEX IF EXISTS app.uq_one_active_share_generation;
DROP INDEX IF EXISTS app.uq_active_contact_email;
DROP INDEX IF EXISTS app.uq_active_contact_name;
