export const TEMPLATE_CODES = [
  "CONTACT_INVITATION",
  "CHECKIN_REMINDER",
  "DEATH_CONFIRMATION_REQUEST",
  "DEATH_CANCELLED_BY_CONTACT",
  "DEATH_CANCELLED_BY_OWNER",
  "DEATH_STAGE2_REMINDER",
  "LEGACY_RELEASED",
  "CONTACT_PASSWORD_CHANGE",
  "OWNER_RECOVERY_START",
  "OWNER_RECOVERY_CONTACT_REQUEST",
  "OWNER_PASSWORD_RESET",
] as const;

export type TemplateCode = (typeof TEMPLATE_CODES)[number];
