export type DesignSource = Readonly<{
  id: string;
  name: string;
  kind: "page" | "email";
  route?: string;
  templateCode?: "DEATH_STAGE2_REMINDER" | "DEATH_CONFIRMATION_REQUEST";
  scenario: "admin" | "anonymous" | "death" | "release" | "legacy";
  sourcePath: string;
  width: number;
  height: number;
  primaryRegion?: Readonly<{ x: number; y: number; width: number; height: number }>;
}>;

export const DESIGN_SOURCES: readonly DesignSource[] = [
  {
    id: "01",
    name: "联系人管理-移动端",
    kind: "page",
    route: "/admin/contacts",
    scenario: "admin",
    sourcePath: "前端设计/01-联系人管理-移动端/screen.png",
    width: 390,
    height: 1033,
  },
  {
    id: "02",
    name: "联系人管理-桌面端",
    kind: "page",
    route: "/admin/contacts",
    scenario: "admin",
    sourcePath: "前端设计/02-联系人管理-桌面端/screen.png",
    width: 1280,
    height: 1232,
  },
  {
    id: "03",
    name: "文件管理-桌面端",
    kind: "page",
    route: "/admin/files",
    scenario: "admin",
    sourcePath: "前端设计/03-文件管理-桌面端/screen.png",
    width: 1280,
    height: 1390,
  },
  {
    id: "04",
    name: "设置-移动端",
    kind: "page",
    route: "/admin/settings",
    scenario: "admin",
    sourcePath: "前端设计/04-设置-移动端/screen.png",
    width: 390,
    height: 1825,
  },
  {
    id: "05",
    name: "释放待定-移动端",
    kind: "page",
    route: "/admin/workflows/current",
    scenario: "release",
    sourcePath: "前端设计/05-释放待定-移动端/screen.png",
    width: 331,
    height: 1600,
  },
  {
    id: "06",
    name: "设置-桌面端",
    kind: "page",
    route: "/admin/settings",
    scenario: "admin",
    sourcePath: "前端设计/06-设置-桌面端/screen.png",
    width: 1161,
    height: 1600,
  },
  {
    id: "07",
    name: "文件管理-移动端",
    kind: "page",
    route: "/admin/files",
    scenario: "admin",
    sourcePath: "前端设计/07-文件管理-移动端/screen.png",
    width: 390,
    height: 1214,
  },
  {
    id: "08",
    name: "管理员首页-移动端",
    kind: "page",
    route: "/admin",
    scenario: "admin",
    sourcePath: "前端设计/08-管理员首页-移动端/screen.png",
    width: 390,
    height: 884,
  },
  {
    id: "09",
    name: "第一阶段确认-桌面端",
    kind: "page",
    route: "/",
    scenario: "death",
    sourcePath: "前端设计/09-第一阶段确认-桌面端/screen.png",
    width: 1280,
    height: 1420,
  },
  {
    id: "10",
    name: "管理员首页-桌面端",
    kind: "page",
    route: "/admin",
    scenario: "admin",
    sourcePath: "前端设计/10-管理员首页-桌面端/screen.png",
    width: 1280,
    height: 749,
  },
  {
    id: "11",
    name: "第一阶段确认-移动端",
    kind: "page",
    route: "/",
    scenario: "death",
    sourcePath: "前端设计/11-第一阶段确认-移动端/screen.png",
    width: 390,
    height: 1554,
  },
  {
    id: "12",
    name: "公开遗书-桌面端",
    kind: "page",
    route: "/legacy",
    scenario: "legacy",
    sourcePath: "前端设计/12-公开遗书-桌面端/screen.png",
    width: 1280,
    height: 1663,
  },
  {
    id: "13",
    name: "公开遗书-移动端",
    kind: "page",
    route: "/legacy",
    scenario: "legacy",
    sourcePath: "前端设计/13-公开遗书-移动端/screen.png",
    width: 390,
    height: 884,
  },
  {
    id: "14",
    name: "最终公开倒计时-邮件",
    kind: "email",
    templateCode: "DEATH_STAGE2_REMINDER",
    scenario: "release",
    sourcePath: "前端设计/14-最终公开倒计时-桌面端/screen.png",
    width: 1600,
    height: 1280,
  },
  {
    id: "15",
    name: "紧急联系人确认-邮件",
    kind: "email",
    templateCode: "DEATH_CONFIRMATION_REQUEST",
    scenario: "death",
    sourcePath: "前端设计/15-紧急联系人确认-邮件入口/screen.png",
    width: 1600,
    height: 1280,
  },
  {
    id: "16",
    name: "释放待定-桌面端",
    kind: "page",
    route: "/admin/workflows/current",
    scenario: "release",
    sourcePath: "前端设计/16-释放待定-桌面端/screen.png",
    width: 1280,
    height: 1310,
  },
] as const;
