import Link from "next/link";
import { StatusBadge } from "../../components/ui/status-badge";
import { formatBeijingDateTime } from "../../lib/time/beijing";
import { ArmingChecklist } from "./arming-checklist";

export type DashboardData = Readonly<{ status: string; lastCheckInAt: string | null; nextDeadlineAt: string | null; activeContacts: number; requiredContacts: number; activePackageVersion: number | null; auditEvents: readonly Readonly<{ id: string; occurredAt: string; summary: string }>[] }>;

export function Dashboard({ data }: Readonly<{ data: DashboardData }>) {
  return <div className="dls-dashboard"><div className="dls-page-heading"><StatusBadge tone={data.status === "ARMED" ? "safe" : "neutral"}>{data.status}</StatusBadge><h1>管理员首页</h1><p>查看签到截止时间、启用条件和最近审计事件。</p></div><div className="dls-dashboard-grid"><section className="dls-panel dls-system-status"><div className="dls-section-heading"><h2>系统状态</h2><StatusBadge tone={data.status === "ARMED" ? "safe" : "neutral"}>{data.status}</StatusBadge></div><dl className="dls-metric-row"><div><dt>最后签到</dt><dd>{data.lastCheckInAt ? formatBeijingDateTime(data.lastCheckInAt) : "尚无签到记录"}</dd></div><div><dt>下次截止</dt><dd>{data.nextDeadlineAt ? formatBeijingDateTime(data.nextDeadlineAt) : "尚未生成截止时间"}</dd></div></dl><div className="dls-checkin-action"><p>签到要求重新输入主密码，成功后按北京时间自然日重置截止周期。</p><Link className="dls-button dls-button--primary" href="/login">验证并签到</Link></div></section><aside className="dls-panel"><h2>系统概况</h2><dl className="dls-summary-list"><div><dt>有效联系人</dt><dd>{data.activeContacts} / {data.requiredContacts}</dd></div><div><dt>当前文件版本</dt><dd>{data.activePackageVersion === null ? "未激活" : `V${data.activePackageVersion}`}</dd></div></dl></aside></div>{data.status !== "ARMED" ? <ArmingChecklist activeContacts={data.activeContacts} activePackageVersion={data.activePackageVersion} requiredContacts={data.requiredContacts} /> : null}<section className="dls-panel"><div className="dls-section-heading"><h2>最近审计</h2><Link href="/admin/audit">查看全部</Link></div>{data.auditEvents.length === 0 ? <p>暂无可显示的审计事件。</p> : <ol className="dls-audit-mini">{data.auditEvents.map((event) => <li key={event.id}><time>{formatBeijingDateTime(event.occurredAt)}</time><span>{event.summary}</span></li>)}</ol>}</section></div>;
}
